export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCESS = 'PRODUCT_LIST_SUCESS'
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE'



export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCESS = 'PRODUCT_DETAILS_SUCESS'
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'